import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/app/globals.css";
import DarkModeProvider from "@/app/DarkModeProvider";
import QueryProvider from "@/app/QueryProvider";
import Header from "@/components/layouts/Header/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <DarkModeProvider>
          <Header />
          <QueryProvider>
            <main className="relative top-12 bg-gray-200 dark:bg-gray-900">
              {children}
            </main>
          </QueryProvider>
        </DarkModeProvider>
      </body>
    </html>
  );
}
